services:
  delivercom.api:
    image: delivercom.api
    build:
      context: .
      dockerfile: src/DeliverCom.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DeliverComDb: "Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres;"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  
  
  
  delivercom.api-1:
    image: delivercom.api-1
    build:
      context: .
      dockerfile: DeliverCom.API/Dockerfile
